version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout

            - run: npm ci
            - run: npm run build
            - run:
                  name: Install JUnit coverage reporter
                  command: npm i -D jest-junit
            - run:
                  name: Run tests with JUnit as reporter
                  command: jest --ci --runInBand --reporters=default --reporters=jest-junit
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: ./reports/
            - store_test_results:
                  path: ./reports/
